### PR TITLE
Added Y_INI, ZCMD and DINI functions.

### PR DESCRIPTION
**Pull request by xman40100**
Also, added a disclaimer for all the SQLite(i) functions to avoid confusion with sa-mp natives. Commits with each addition were done individually.

### CODE REVIEW

**Comment by EOussama** [comment]
Just for consistancy, can you run the snippet files through a JSON formater?

**Comment by xman40100** [comment]
Alright. I'll be on later in my computer so I can do it.

**Comment by xman40100** [comment]
[These are the results](https://imgur.com/a/7BpFCiy). They were ran through [Curious Concepts' JSON formatter and validator](https://jsonformatter.curiousconcept.com/) with the ECMA-404 JSON standard.

**Comment by Southclaws** [comment]
Thanks for the contribution!

**Pull request merged**
